blogapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('stock.urls')),
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social'))
]

stock/urls.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 17 11:47:44 2018

@author: carol
"""

from django.urls import path
from django_filters.views import FilterView
from .filters import ProductFilter, PostFilter
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('products/add/',
         views.ProductCreate.as_view(),
         name='product-add'),
    path('products/<int:pk>/update/',
         views.ProductUpdate.as_view(),
         name='product-update'),
    path('products/<int:pk>/delete/',
         views.ProductDelete.as_view(),
         name='product-delete'),
    path('products/<int:pk>/',
         views.ProductDetail.as_view(),
         name='product-detail'),

    path('products/all/',
         views.ProductListView.as_view(),
         name='product-list'),

    path('products/search/',
         FilterView.as_view(filterset_class=ProductFilter,
                            template_name='product-list'),
         name='product-filter'),

    path('products/accesories/',
         views.AccesoriesListView.as_view(),
         name='accesories-list'),
    path('products/skincare/',
         views.SkincareListView.as_view(),
         name='skincare-list'),
    path('products/nailpolish/',
         views.NailpolishListView.as_view(),
         name='nailpolish-list'),
    path('products/makeup/',
         views.MakeupListView.as_view(),
         name='makeup-list'),
    path('products/parfum/',
         views.ParfumListView.as_view(),
         name='parfum-list'),

    path('products/nonfinished/',
         views.NonfinishedListView.as_view(),
         name='nonfinished-list'),
    path('products/projectpan/',
         views.ProjectPanListView.as_view(),
         name='projectpan-list'),

    path('products/product_graph/',
         views.product_graph,
         name='product-graph'),

    # Posts urls
    path('posts/add/',
         views.PostCreate.as_view(),
         name='post-add'),
    path('posts/<int:pk>/update/',
         views.PostUpdate.as_view(),
         name='post-update'),
    path('posts/<int:pk>/delete/',
         views.PostDelete.as_view(),
         name='post-delete'),
    path('posts/<int:pk>/',
         views.PostDetail.as_view(),
         name='post-detail'),
    path('posts/all/',
         views.PostListView.as_view(),
         name='post-list'),
    path('posts/posted/',
         views.PostedListView.as_view(),
         name='posted-list'),
    path('posts/draft/',
         views.DraftListView.as_view(),
         name='draft-list'),

    # Load posts
    path('posts/get_posts/',
         views.get_posts,
         name='get-list'),

    path('posts/send_mail_post',
         views.send_mail_post,
         name='send-list'),
    ]

stock/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator

from datetime import datetime
import urllib
import os
from django.conf import settings
from .constants import CATEGORY, FINISH, COLOR, CURRENCY, QUALITY, STATUS
from .constants import GENERIC_LIST, PROJECTPAN_LIST, NAILS_LIST, NAILPOLISH_LIST
from .utils import generate_hashtags
# Create your models here.


class Product(models.Model):
    product = models.CharField(max_length=150,
                               verbose_name='Product')
    brand = models.CharField(max_length=100,
                             verbose_name='Brand')
    collection = models.CharField(max_length=100,
                                  verbose_name='Collection',
                                  blank=True,
                                  null=True)
    category = models.CharField(max_length=100,
                                choices=CATEGORY,
                                verbose_name='Category')
    finish = models.CharField(max_length=50,
                              choices=FINISH,
                              verbose_name='Finish',
                              blank=True,
                              null=True)
    color = models.CharField(max_length=30,
                             choices=COLOR,
                             verbose_name='Color',
                             blank=True,
                             null=True)
    bought_date = models.DateField(verbose_name='Bought date',
                                   blank=True,
                                   null=True)
    expiration_date = models.CharField(max_length=3,
                                       verbose_name='Expiration date')
    currency = models.CharField(max_length=3,
                                choices=CURRENCY,
                                verbose_name='Currency',
                                blank=True,
                                null=True)
    price = models.DecimalField(max_digits=7,
                                decimal_places=2,
                                verbose_name='Price',
                                blank=True,
                                null=True)
    duration = models.CharField(max_length=20, choices=QUALITY,
                                verbose_name='Duration',
                                blank=True,
                                null=True)
    quality = models.CharField(max_length=20, choices=QUALITY,
                               verbose_name='Quality',
                               blank=True,
                               null=True)
    project_pan = models.BooleanField(verbose_name='Project pan')
    percentage_used = models.IntegerField(default=0.0,
                                          validators=[
                                                  MaxValueValidator(100),
                                                  MinValueValidator(0)
                                                  ],
                                          verbose_name='Percentage used')
    finished = models.BooleanField(verbose_name='Finished',
                                   default=False)
    status = models.CharField(max_length=10,
                              choices=STATUS,
                              verbose_name='Status',
                              default='Draft')
    upload_path = 'media/product'
    image = models.ImageField(upload_to=upload_path, null=True, blank=True)
    image_url = models.URLField(null=True, blank=True)

    class Meta:
        ordering = ['product', 'brand', 'category']

    def __str__(self):
        return self.product

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if self.image_url:
            file_save_dir = self.upload_path
            filename = urllib.parse(self.image_url).path.split('/')[-1]
            urllib.urlretrieve(self.image_url,
                               os.path.join(file_save_dir, filename))
            self.image = os.path.join(file_save_dir, filename)
            self.image_url = ''
            self.brand = filename.split('_')[0]
        super(Product, self).save()


class Post(models.Model):
    blogger_id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100,
                             verbose_name='Title')
    brand = models.CharField(max_length=100,
                             verbose_name='Brand')
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                verbose_name='Product',
                                null=True)
    tags = models.CharField(max_length=300,
                            verbose_name='Tags',
                            null=True)
    hashtags = models.CharField(max_length=300,
                                verbose_name='Hashtags',
                                null=True,
                                blank=True)
    link = models.URLField(max_length=200,
                           verbose_name='Link')
    date = models.DateField(verbose_name='Posted date',
                            null=True)
    status = models.CharField(max_length=10,
                              choices=STATUS,
                              verbose_name='Status',
                              default='Draft')
    ig = models.BooleanField(verbose_name='Published on IG',
                             default=False)
    co = models.BooleanField(verbose_name='Comments replied',
                             default=False)
    upload_path = 'media/post'
    image_url = models.URLField(null=True, blank=True)

    class Meta:
        ordering = ['-date']
        get_latest_by = ['-date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

    def clean(self):
        if getattr(self, 'hashtags', None) is None:
            if any(ext in self.title for ext in ['Project', 'Terminados', 'Empties']):
                self.hashtags = 'Project Pan update! ' + GENERIC_LIST + PROJECTPAN_LIST
            elif 'Nail Art' in self.title:
                self.hashtags = GENERIC_LIST + ' #'.join(NAILPOLISH_LIST) + NAILS_LIST
            else:
                self.hashtags = generate_hashtags(self.product)
        if self.status == 'draft' and self.pub_date is not None:
            raise ValidationError('Drafts may not have a publication date.')
        if self.status == 'published' and self.pub_date is None:
            self.pub_date = datetime.date.today()

templates/products/detail.html
{% extends "base.html" %}
{% block content %}
<!-- row -->
<div class="row tm-mt-big">
    <div class="col-xl-8 col-lg-10 col-md-12 col-sm-12">
        <div class="bg-white tm-block">
            <div class="row">
                <div class="col-12">
                    <h2 class="tm-block-title d-inline-block">Detail</h2>
                </div>
            </div>
            <div class="row mt-4 tm-edit-product-row">
                <div class="col-xl-7 col-lg-7 col-md-12">
                    <form action="" class="tm-edit-product-form">
                        <div class="input-group mb-3">
                            <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Product</label>
                            <input placeholder="Product name" value={{ product.product }} id="name" name="name" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7">
                        </div>
                        <div class="input-group mb-3">
                            <label for="description" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 mb-2">Description</label>
                            <textarea class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7" rows="3" placeholder="Product Description" required>Fusce finibus dui tellus.</textarea>
                        </div>
                        <div class="input-group mb-3">
                            <label for="category" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Category</label>
                            <select class="custom-select col-xl-9 col-lg-8 col-md-8 col-sm-7" id="category">
                                <option value="1" selected>Cras efficitur lacus</option>
                                <option value="2">Pellentesque molestie</option>
                                <option value="3">Sed feugiat nulla</option>
                            </select>
                        </div>
                        <div class="input-group mb-3">
                            <label for="expire_date" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Expire
                                Date
                            </label>
                            <input placeholder="Expire Date" value="2018-10-28" id="expire_date" name="expire_date" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7"
                                data-large-mode="true">
                        </div>
                        <div class="input-group mb-3">
                            <label for="stock" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Units In
                                Stock
                            </label>
                            <input placeholder="Stock" value="255" id="stock" name="stock" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-7 col-sm-7">
                        </div>
                        <div class="input-group mb-3">
                            <div class="ml-auto col-xl-8 col-lg-8 col-md-8 col-sm-7 pl-0">
                                <button type="submit" class="btn btn-primary">Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-xl-4 col-lg-4 col-md-12 mx-auto mb-4">
                    <img src="{{ product.picture }}" alt={{ product.product }} class="img-fluid mx-auto d-block">
                    <div class="custom-file mt-3 mb-3">
                        <input id="fileInput" type="file" style="display:none;" />
                        <input type="button" class="btn btn-primary d-block mx-auto" value="Upload ..." onclick="document.getElementById('fileInput').click();"
                        />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/products/form.html
{% extends "base.html" %}
{% block js %}

{% endblock %}
{% block content %}
<div class="container" style="position: relative;">
<form action="" method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save" />
</form>
<script>
    $(function () {
        $('#id_bought_date').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>
</div>
{% endblock %}

templates/products/list.html
{% extends "base.html" %}
{% block content %}
<!-- row -->
<div class="row tm-content-row tm-mt-big">
    <div class="col-xl-8 col-lg-12 tm-md-12 tm-sm-12 tm-col">
        <div class="bg-white tm-block h-100">
            <div class="row">
                <div class="col-md-8 col-sm-12">
                    <h2 class="tm-block-title d-inline-block">Products</h2>

                </div>
                <div class="col-md-4 col-sm-12 text-right">
                    <a href="form.html" class="btn btn-small btn-primary">Add New Product</a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover table-striped tm-table-striped-even mt-3">
                    <thead>
                        <tr class="tm-bg-gray">
                            <th scope="col"><i class="fas fa-check"></i></th>
                            <th scope="col"><i class="fas fa-camera-retro"></i></th>
                            <th scope="col">Brand</th>
                            <th scope="col">Name</th>
                            <th scope="col" class="text-center">Used</th>
                            <th scope="col" class="text-center">Category</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for product in object_list %}
                        <tr>
                            <th scope="row">
                                <input type="checkbox" aria-label="Checkbox">
                            </th>
                            <td><img src="{{ product.picture }}"></td>
                            <td class="tm-product-name">{{ product.brand }}</td>
                            <td class="text-left"><a href='{% url "product-detail" product.pk %}'>{{ product.product }}</td>
                            <td class="text-center">{{ product.percentage_used }}%</td>
                            <td class="text-center">{{ product.get_category_display }}</td>
                        </tr>
                    {% empty %}
                    <li>No products. Time to go shopping!</li>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="tm-table-mt tm-table-actions-row">
                <div class="tm-table-actions-col-left">
                    <button class="btn btn-danger">Mark as finished</button>
                </div>
                <div class="tm-table-actions-col-right">
                    {% if is_paginated %}
                    <span class="tm-pagination-label">Page</span>
                    <nav aria-label="Page navigation" class="d-inline-block">
                        <ul class="pagination tm-pagination">
                            {% if page_obj.has_previous %}
                              <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                              <li class="page-item active"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in paginator.page_range %}
                              {% if i <= page_obj.number|add:3 and i >= page_obj.number|add:-3 %}
                                  {% if page_obj.number == i %}
                                    <li class="page-item active"><span> <span class="page-link">{{ i }}</span></span></li>
                                  {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                  {% endif %}
                              {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                              <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                            {% else %}
                              <li class="page-item active"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-4 col-lg-12 tm-md-12 tm-sm-12 tm-col">
        <div class="bg-white tm-block h-100">
            <h2 class="tm-block-title d-inline-block">Product Categories</h2>
            <table class="table table-hover table-striped mt-3">
                <tbody>
                {% for product in object_list|dictsort:'category' %}
                    {% ifchanged %}
                    <tr>
                        <td><form method="get">
                          {{ filter.form.as_p }}
                          <button type="submit" class="btn btn-primary">{{ product.category }}</button>
                        </form></td>
                    </tr>
                    {% endifchanged %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/products/product_graph.html
{% extends "base.html" %}
{% block content %}
<div>
    <div class="row tm-content-row tm-mt-big">
        <div class="col-lg-12 tm-md-12 tm-sm-12 tm-col">
            <div class="bg-white tm-block h-100">
                {{ the_div|safe }}
            </div>
            {{ the_script|safe }}
        </div>
    </div>
</div>
{% endblock %}